### ISSUE TITLE
improve getting infantry role more efficiently

### ISSUE THREAD

**Issue by Fusselwurm** [Dahlgren/ar3play-addon#2]
(narf, cant create issues on a fork - sry)

*Creedcoder* is currently briefing me on performance. 

I should use: 
* `getText(configFile >> "CfgVehicles" >> typeOf _x >> "displayName")` to get infantry role (its i18n'd, dangerous)
* `vehicleClass`
*  `getPosASL `
* `str( side _unit)`

**Comment by Dahlgren** [comment]
I guess we should move my original repo to your account/organisation and I'll have a fork instead. Simplifies making pull requests for me as well. Highlight me on IRC and we'll sort it out!

**Comment by Fusselwurm** [comment]
moved this issue to my fork.
